#PBS -N KRAS docking validation
#PBS -l walltime=06:00:00
#PBS -j oe
#PBS -l select=1:ncpus=48:mem=96gb

cd $PBS_O_WORKDIR

# Load the specific module found in your list
module load miniconda/4.9

# Activate your environment
source activate /home/svu/e0324493/kras_prediction/kras_env

# Run your parallel script
python molecular_docking_validation.py mol_docking/apo_protein_clean.pdb mol_docking/ligand_xtal.pdb mol_docking/chembl_known_actives.csv mol_docking/chembl_known_inactives.csv 48
