#PBS -N KRAS_Prediction
#PBS -l walltime=06:00:00
#PBS -j oe
#PBS -l select=1:ncpus=48:mem=96gb

cd $PBS_O_WORKDIR

# Load the specific module found in your list
module load miniconda/4.9

# Activate your environment
source activate /home/svu/e0324493/kras_prediction/kras_env

# Run your parallel script
python qsar_pipeline_hpc.py optimised_SVR_CombinedFP.joblib DATASET_fingerprints_combined_train.csv $LIBRARY 48
